### ISSUE TITLE
Can you provide your hardware specifications?

### ISSUE THREAD

**Issue by jash-maester** [AntonioAlgaida/Edge.SRGAN#1]
Hello, I am a student and out of curiosity I tried to execute your program. and I am getting Out of memory issues with a RTX 2060 6GB vRAM. What is the actual requirement for the Testing and Training, may I know?

**Comment by AntonioAlgaida** [comment]
Hi Jash,
The requirements to run the training depend on the size of the images you are using. I was using patch images of about 24 pixels in low resolution (although I am varying the batch size later, note the data_loader.py file, line 145) and a batch of 8 images. I had a GTX 1050TI with 4GB of memory. 
If you need help running it, let me know.

**Comment by jash-maester** [comment]
Yeah Hi and thanks for your resolution, so I was training with the DIV2K dataset, and found that the results were not satisfiable with  Batch Size of16. (Which I did on an AWS instance, BTW.) Then I sort of abandoned the project. How were your results from inference? The SSIM was almost similar to yours but alas couldn't retrieve any valuable image as an output from the testing/inference.
PS: I modified your code and made it to run on AWS instance. Its just that I found your idea fascinating.

**Comment by AntonioAlgaida** [comment]
Hi Jash, 
It would be great if you could make a fork of the project and upload the modifications you have made to make it work with AWS, so both projects gain visibility. 
And if you also leave a star, it would be really nice.
The result was an SSIM around 0.88

**Comment by jash-maester** [comment]
Sure, Umm I will upload it tomorrow cuz according to my timezone its a little bit late tonight.
